pretrained_model_name_or_path: "unsloth/gemma-3-4b-pt"
tokenizer_name_or_path: null
trust_remote_code: true

max_seq_length: 4096
torch_dtype: "bfloat16"
attn_implementation: null
gradient_checkpointing: true
use_cache: false

quantization:
  load_in_4bit: false
  bnb_4bit_compute_dtype: "bfloat16"
  bnb_4bit_quant_type: "nf4"
  bnb_4bit_use_double_quant: true

